name: Main

on: [push,pull_request,workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    container: ruby:${{ matrix.ruby }}

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        ruby:
          - 2.7.7
          - 3.0.5
        gemfile:
          - gemfiles/activerecord_6.0.x.gemfile
          - gemfiles/activerecord_6.1.x.gemfile
        exclude:
          - ruby: 3.0.5
            gemfile: gemfiles/activerecord_6.0.x.gemfile

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      env:
        BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      run: |
        gem install bundler -v '~> 2.2.15'
        bundle install --jobs 4 --retry 3

    - name: Run the default task
      env:
        BUNDLE_GEMFILE: ${{ matrix.gemfile }}
        DB_HOST: postgres
        DB_USER: postgres
        DB_PASS: postgres
      run: rake
